spring:
    datasource:
        url: ${POSTGRES_DATABASE}
        #url: jdbc:postgresql://postgres:DGTcwQoZZYMNvlQXStJbgYAMIOwHAYcX@postgres.railway.internal:5432/railway
        #username: ${PGUSER}
        #password: ${PGPASSWORD}
    jpa:
        open-in-view: false
        hibernate:
            ddl-auto: create # validate | update | create | create-drop
